apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-pod-probes
  annotations:
    pod-policies.kyverno.io/autogen-controllers: DaemonSet,Deployment,StatefulSet
    policies.kyverno.io/title: Require Pod Probes
    policies.kyverno.io/category: Best Practices, EKS Best Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      Liveness and readiness probes need to be configured to correctly manage a Pod's
      lifecycle during deployments, restarts, and upgrades.
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: validate-probes
      preconditions:
        any:
          - key: "{{ to_string(request.object.metadata.ownerReferences[?kind=='Job']) }}"
            operator: Equals
            value: "null"
          - key: "{{ to_string(request.object.metadata.ownerReferences[?kind=='Job']) }}"
            operator: Equals
            value: "[]"
        all:
          - key: "{{request.operation || 'BACKGROUND'}}"
            operator: AnyIn
            value:
              - CREATE
              - UPDATE
      match:
        any:
          - resources:
              kinds:
                - Pod
      exclude:
        any:
          - resources:
              namespaces:
                - argocd
                - cert-manager
                - kube-system
                - kyverno
                - monitoring
      validate:
        message: "Liveness or readiness probes are required for all containers."
        foreach:
          - list: request.object.spec.containers[]
            deny:
              conditions:
                all:
                  - key: livenessProbe
                    operator: AllNotIn
                    value: "{{ element.keys(@)[] }}"
                  - key: readinessProbe
                    operator: AllNotIn
                    value: "{{ element.keys(@)[] }}"
