version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/terraform"
    target-branch: "main"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Santiago"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "terraform"
    commit-message:
      prefix: "deps(terraform)"
      include: "scope"
    groups:
      terraform-providers:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
