apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoria-logs
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  source:
    repoURL: https://victoriametrics.github.io/helm-charts/
    chart: victoria-logs-single
    targetRevision: 0.11.26
    helm:
      releaseName: vlogs
      values: |
        server:
          replicaCount: 1
          retentionPeriod: 7
          persistentVolume:
            enabled: true
            storageClassName: local-path
            accessModes:
              - ReadWriteOnce
            size: 10Gi
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
