apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Platform bootstrap — root app of apps
  sourceRepos:
    - https://github.com/felipe-veas/homelab-platform.git
  destinations:
    - namespace: argocd
      server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
    - group: argoproj.io
      kind: Application
