apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-policies
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  ignoreDifferences:
    - group: kyverno.io
      kind: ClusterPolicy
      jqPathExpressions:
        - .metadata.managedFields
        - .metadata.generation
        - .metadata.resourceVersion
        - .status
  project: infrastructure
  sources:
    - path: apps/kyverno/policies
      repoURL: https://github.com/felipe-veas/homelab-platform.git
      targetRevision: HEAD
      directory:
        recurse: true
    - chart: kyverno-policies
      repoURL: https://kyverno.github.io/kyverno
      targetRevision: "3.7.0"
      helm:
        releaseName: kyverno-policies
        values: |
          validationFailureAction: Enforce
          podSecurityStandard: baseline
          policyExclude:
            require-run-as-nonroot:
              any:
              - resources:
                  namespaces:
                  - monitoring
                  - kube-system
                  - logging
            disallow-capabilities:
              any:
              - resources:
                  namespaces:
                  - monitoring
                  - kube-system
                  - logging
            disallow-capabilities-strict:
              any:
              - resources:
                  namespaces:
                  - monitoring
                  - kube-system
                  - logging
            disallow-host-namespaces:
              any:
              - resources:
                  namespaces:
                  - monitoring
                  - kube-system
                  - logging
            disallow-host-path:
              any:
              - resources:
                  namespaces:
                  - monitoring
                  - kube-system
                  - logging
            disallow-host-ports:
              any:
              - resources:
                  namespaces:
                  - monitoring
                  - kube-system
                  - logging
            disallow-privilege-escalation:
              any:
              - resources:
                  namespaces:
                  - monitoring
                  - kube-system
                  - logging
            require-run-as-non-root-user:
              any:
              - resources:
                  namespaces:
                  - monitoring
                  - kube-system
                  - logging
            restrict-seccomp-strict:
              any:
              - resources:
                  namespaces:
                  - monitoring
                  - kube-system
                  - logging
            restrict-volume-types:
              any:
              - resources:
                  namespaces:
                  - monitoring
                  - kube-system
                  - logging
  destination:
    namespace: kyverno
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
